Repository zotbins/Waste-Watcher-AWS-IoT-Core, pull requests merged in 2021-11, with the labels that each got.

#14 Updated README to address GitHub repo name change
  README.md
Labels: documentation

#13 Created MQTT test scripts
  mqtt_test/.env.txt
  mqtt_test/.gitignore
  mqtt_test/README.md
  mqtt_test/config.py
  mqtt_test/mqtt_pub.py
  mqtt_test/mqtt_sub.py
  mqtt_test/requirements.txt
  mqtt_test/test_image.jpg
Labels: code improvement

#15 Fixed ultrasonic library bug & created ultrasonic unit test
  include/config.h.txt
  include/fullness.h
  lib/ultrasonic/ultrasonic.c
  src/fullness.c
  test/main.c
Labels: bug

#16 Andrea fullness
  src/fullness.c
  src/main.c
Labels: new feature

#22 Refactored code to use ESP-IDF's provided error codes & error handling
  include/fullness.h
  include/photo.h
  src/fullness.c
  src/main.c
  src/photo.c
Labels: code improvement
